package com.company;

import java.io.PrintWriter;

public class Main {

    // Первое Spring REST приложение.

    // Создадим новое Spring Boot приложение в Spring Initializr.
    // Добавим 4 зависимости:
    // - Spring Web (сюда входит и Jackson);
    // - Thymeleaf;
    // - Spring Data JPA;
    // - PostgreSQL Driver.

    // Создадим контроллер FirstRESTController, который будет возвзращать данные.
    // Создадим контроллер PeopleController, который будет возвращать список из объектов.

    // Создадим таблицу Person.
    // create table Person(
    //     id int generated by default as identity primary key,
    //     name varchar(100) not null,
    //     age int,
    //     email varchar(100)
    // )

    // Добавим в таблицу Person несколько людей.
    // insert into person(name, age, email) values ('Tom', 25, 'tom@mail.ru');
    // insert into person(name, age, email) values ('Bob', 51, 'bob@mail.ru');
    // insert into person(name, age, email) values ('katy', 38, 'katy@mail.ru');


}
